
CondaError: Run 'conda init' before 'conda deactivate'

2024-07-19 14:18:53,526 - __main__ - INFO - Loading variable(s): labelled_gaze_positions_m1
INFO:__main__:Loading variable(s): labelled_gaze_positions_m1
2024-07-19 14:18:54,099 - __main__ - INFO - M1 remapped gaze pos data acquired!
INFO:__main__:M1 remapped gaze pos data acquired!
2024-07-19 14:18:54,099 - __main__ - INFO - Recomputing variable(s): labelled_fixations_m1, labelled_saccades_m1
INFO:__main__:Recomputing variable(s): labelled_fixations_m1, labelled_saccades_m1
INFO:root:Job commands in the job list: 31
INFO:root:Successfully generated the dSQ job script
INFO:root:Using dSQ job script: ./job_scripts/dsq-joblist_fixations.sh
INFO:root:Successfully submitted jobs using sbatch for script ./job_scripts/dsq-joblist_fixations.sh
INFO:root:Submitted job array with ID: 27330639
INFO:root:Tracking progress of job array with ID: 27330639
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 is still running. Checking again in 30 seconds...
INFO:root:Job array 27330639 has completed.
INFO:root:Saving: /gpfs/milgram/project/chang/pg496/data_dir/otnal/processed_data/all_fixations_and_saccades.pkl
2024-07-19 17:26:33,324 - __main__ - INFO - M1 fixations and saccades acquired
INFO:__main__:M1 fixations and saccades acquired
Traceback (most recent call last):
  File "/gpfs/milgram/project/chang/pg496/conda_envs/gaze_processing/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'start_index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "analyze_gaze_signals.py", line 195, in <module>
    main()
  File "analyze_gaze_signals.py", line 192, in main
    data_manager.run()
  File "analyze_gaze_signals.py", line 126, in run
    self.plot_fixations_in_gaze_snippets()
  File "analyze_gaze_signals.py", line 86, in plot_fixations_in_gaze_snippets
    plotter.plot_fixations_and_saccades(
  File "/gpfs/milgram/pi/chang/pg496/repositories/social_gaze_mech_otnal/plotter.py", line 77, in plot_fixations_and_saccades
    start_index = max(0, fixation['start_index'] - 6)
  File "/gpfs/milgram/project/chang/pg496/conda_envs/gaze_processing/lib/python3.8/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/gpfs/milgram/project/chang/pg496/conda_envs/gaze_processing/lib/python3.8/site-packages/pandas/core/series.py", line 989, in _get_value
    loc = self.index.get_loc(label)
  File "/gpfs/milgram/project/chang/pg496/conda_envs/gaze_processing/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'start_index'
